### ISSUE TITLE
Protection > IV

### ISSUE THREAD

**Issue by BentoGambin** [ToMe25/LootingVI#3]
Hi, first of all, great mod, but there seems to be an issue:
All the protection enchantments cannot be stacked more than a level 4, even if the config says they should be able to.
Thanks in advance.
![2020-01-17_13 01 30](https://user-images.githubusercontent.com/41645690/72622247-9a151b80-3921-11ea-834f-aa7b0dc267a0.png)
![2020-01-17_13 01 27](https://user-images.githubusercontent.com/41645690/72622249-9a151b80-3921-11ea-81c5-9e7bbb6c9494.png)
![2020-01-17_13 01 29](https://user-images.githubusercontent.com/41645690/72622250-9a151b80-3921-11ea-8a4e-df7a7acace3b.png)
![image](https://user-images.githubusercontent.com/41645690/72622298-b0bb7280-3921-11ea-8a02-ab45e16f2ba7.png)

**Comment by ToMe25** [comment]
Please list all the mods and their versions needed to reproduce this issue, as i can't reproduce it with just the newest version of this mod.

**Comment by BentoGambin** [comment]
Shure! 
BTW the mods that have "###" are for shure or possibly related with enchantments.

AmbientSounds_v3.0.14_mc1.14.4.jar"
OptiFine-1.14.4_HD_U_F5.jar"
###Quark-r2.0-208.jar"
MutantBeasts-1.14.4-0.7.0.jar"
MixinBootstrap-1.0.0.jar"
ExtraGems-1.14.4-(v.2.0.3).jar"
Jei-1.14.4-6.0.0.27.jar"
essentials-1.14.4-2.6.5.jar"
ScalingHealth-1.14.4-2.3.9+35.jar"
grindr-1.0.1.jar"
tubesreloaded-1.14.4-1.1.1c.jar"
immersive-portals-0.10(for+mc+1.14+with+forge).jar"
BetterCaves-1.14.4-1.1.1.jar"
Blur-1.1.0-1.jar"
\CarryOn+MC1.14.4+v1.12.4.jar"
\cofh_core-1.14.4-0.2.0b.jar"
ruins-1.14.4.6.jar"
DungeonCrawl-1.14.4-1.6.0.jar"
mysticallib-1.14.4-1.13.0.jar"
SilentLib-1.14.4-4.4.0+44.jar"
randompatches-1.14.4-1.19.1.1.jar"
OreExcavation-1.6.145.jar"
Waystones_1.14.4-5.0.2.jar"
traverse-1.14.4-2.0.3.jar"
ironchest-1.14.4-9.1.5.jar"
infernalmobs-1.14.4.6.jar"
###randomenchants-2.2.3.jar"
###ensorcellation-1.14.4-0.2.0b.jar"
Placebo-1.14.4-2.3.5.jar"
###VTweaks-1.14.4-3.1.3.jar"
smooth-scrolling-everywhere-1.1.jar"
endteleporters-1.1.1-1.14.4.jar"
corpse-1.14.4-1.0.3.jar"
craftingstation-2.1.3c.jar"
AutoRegLib-1.4-35.jar"
MouseTweaks-2.13-mc1.14.4.jar"
fishtraps-0.0.4.jar"
FTBUtilitiesBackups-2.0.0.11.jar"
###anviltweaks-1.4a.jar" (should be related but problem appeared way before adding this one)
KleeSlabs_1.14.4-7.4.8.jar"
Uppers-0.1.11.jar"
AppleSkin-mc1.14.4-forge-1.0.13.jar"
performant-1.14.4-1.4.jar"
ToastControl-1.14.4-2.2.0.jar"
AI-Improvements-1.14.4-0.3.0.jar"
EnchantmentDescriptions-1.14.4-1.3.8.jar"
###LootingModMC1.14.4-1.0.1.jar"
FastFurnace-1.14.4-2.2.4.jar"
modnametooltip_1.14.3-1.12.1.jar"
FastLeafDecay-v17.jar"
AttributeFix-1.14.4-3.0.2.jar" (was also added after the problem appeared)
Nutritious Milk_1.14-1.0.jar"

**Comment by BentoGambin** [comment]
So, I did some tests and found out that removing ensorcellation fixes this. Now I'm gonna look for something in the config of said mod and will report back if I have any findings.

**Comment by BentoGambin** [comment]
ANDDD.... turns out:
![image](https://user-images.githubusercontent.com/41645690/72670076-f0fd1c80-3a17-11ea-841d-66f085c56b97.png)
LOL, really sorry for the waste of time and best of luck my friend. It's fixed!

**Comment by ToMe25** [comment]
No problem, nice that you found out and best of luck :)
