### ISSUE TITLE
Looting X well Looting XI ... oh wait Looting XII....

### ISSUE THREAD

**Issue by depunkt2k** [ToMe25/LootingVI#5]
//Bad english incoming
When i apply looting 10 on a sword its the maximum amount there are books for in JEI, ok then i tried and combined looting 10 and looting 10 (books) in an anvil. and well i got an looting 11 book. "thooo..." i thought lets try two books looting 11 and looting 11. well nothing. just no valid recipe.
then i combined a looting 11 book and a sword, you guessed it: looting 11 sword. then i combined two looting 11 swords in an anvil. well ... looting 12 sword. what is that? it's just not fun

**Comment by depunkt2k** [comment]
![grafik](https://user-images.githubusercontent.com/64969511/81303521-1623a280-907c-11ea-936a-980243e3135e.png)
![grafik](https://user-images.githubusercontent.com/64969511/81303628-3ce1d900-907c-11ea-934c-62b218798442.png)
![grafik](https://user-images.githubusercontent.com/64969511/81303730-613db580-907c-11ea-8982-c107a82e6a28.png)
![grafik](https://user-images.githubusercontent.com/64969511/81303768-6dc20e00-907c-11ea-902e-f5bd23b40b53.png)
![grafik](https://user-images.githubusercontent.com/64969511/81303820-8500fb80-907c-11ea-8c0c-e021dd0f1894.png)
![grafik](https://user-images.githubusercontent.com/64969511/81303964-b4176d00-907c-11ea-81d9-e8deb9929b47.png)
![grafik](https://user-images.githubusercontent.com/64969511/81304017-c5607980-907c-11ea-922b-dbac89c20c7e.png)
![grafik](https://user-images.githubusercontent.com/64969511/81304366-43248500-907d-11ea-8696-0b3f0ce5eba0.png)

**Comment by ToMe25** [comment]
are you sure this is caused by this mod?
i know about other mods that also mess with the max level of enchantments, and you seem to use atleast a few other mods.
Please tell me the minecraft version you are playing, the version of this mod, and a list of all the other used mods, so i can try and reproduce this.
also please try and reproduce this with as little mods as possible.

**Comment by depunkt2k** [comment]
I fixed it i think.. kind of..
i'm glad to tell you its not your mod so this thread can be closed.
Its "Quark" (Mod)
In quark there is a book named Ancient Tome
https://ftb.gamepedia.com/Ancient_Tome
it allowes you to enchant a book one level higher as intended. But (so i think) destroyes everything obove.
Yes you are right i have installed a lot of mods wich are messing with enchantments, i am really sorry that i reduced the problem to your mod.
Thanks alot anyway!

Oh the minecraft V1.12.2 and a mod list isn't that easy i testet everything yesterday many hours it worked great when i disabled that Ancient Tome. It must be some kind of dirty programming there...

**Comment by ToMe25** [comment]
nice that you found the issue :)
