### ISSUE TITLE
Love the mod

### ISSUE THREAD

**Issue by DistortedEnn** [ToMe25/LootingVI#6]
Im having a bit of trouble trying to find where i can configure it, sorry for wasting your time and the dumb question im just very unsure

**Comment by ToMe25** [comment]
In which minecraft version are you using this mod?
Depending on your minecraft version you are either looking for a file called `lootingmod.cfg` or `lootingmod.toml` in the config folder next to your mods folder.
In that file you find a bunch of configuration options(2 per Enchantment class) that you can adjust to change the max level of the enchantements and the min enchantability, which is a value that controls for how many levels you can get the enchantment.

**Comment by ToMe25** [comment]
its been almost two weeks since you asked this question, and as i consider it fully answered i will close this issue now.
You will probably have to mention me for github to notify me should you want to tell me anything in this issue.
